apiVersion: v1       
entries:            
  app1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-06-17T07:57:18.365804188Z"
    description: A Helm chart for Kubernetes
    digest: a95eb0440a3fa4de44775f830feca609bf52cf513ec806a8e025f2f2824ec6e5
    name: app1
    type: application
    urls:
    - app1-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-17T07:57:18.365055181Z"





