name: Docker Build and Push

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret Values
        run: |
      #    echo "API_KEY: ${{ secrets.API_KEY }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
          
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t rg850/demo:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push rg850/demo:latest
